on:
  workflow_dispatch:
    branches:
      - "master"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: keep-jbl-go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
